### PR TITLE
Remove dependency on microtime-nodejs

### PR DESCRIPTION
**Pull request by huksley**

### CODE REVIEW

**Review by peterkhayes — CHANGES_REQUESTED** [review]
This looks great, but I have a few suggestions that I think would simplify things:

* Rename the `now` as `getCurrentMicroseconds`. The `now` name comes from the `microtime-nodejs` library; I don't see why we need to keep that name but also rename the import in `index.ts`.
* Inline the `getCurrentMicrotime` function at the bottom of `index.ts`. I think you're only doing this so it can be stubbed, but there's a better approach I think.
* Instead of spying on `now.now`, instead spy on `process.hrtime`. This helps validate that the `getCurrentMicrotime` implementation works as intended.

**Comment by huksley** [comment]
> I think you're only doing this so it can be stubbed, but there's a better approach I think.

you absolutely right, that was the only reason I've done this :) 
I forgot to think about stubbing process.hrtime, so resorted to putting it to separate file

fixed

**Review by peterkhayes — APPROVED** [review]
Awesome - this looks great! I'll merge and publish

**Comment by peterkhayes** [comment]
This is published as [0.2.12](https://www.npmjs.com/package/rolling-rate-limiter/v/0.2.12)

**Comment by peterkhayes** [comment]
FYI this was reverted due to the issue above.

**Pull request merged**
