### PR TITLE
Add function to check current rate limit counters

### LINKED ISSUE #38: Add ability to check remaining requests without incrementing counter
I'm working to update the rate limiting on a login endpoint to look something like this:

1) Check if rate limit exceeded (without incrementing counter). If rate limit has been exceeded block the request.
2) Process login request
3) If login request failed, increment the rate limit counter.

Essentially I just want to rate limit the route based on how many failed login attempts occur. In order to do this I need to be able to check the current rate limit at the beginning of the request without adding an entry to the counter.

At the end of a failed request I will then call the normal `limiter` function to increment the rate limit counter.

For the redis implementation a new function could be added that uses the current multi without the `zadd` command.

Is this something you're open to adding to this lib? If so, I can put together a PR.

### PR DESCRIPTION
**Pull request by jkirkwood**
Closes #38 

This PR adds a `check` function that allows a user to get the current counter value for a rate limiter without incrementing it.

### CODE REVIEW

**Comment by jkirkwood** [comment]
@peterkhayes anything I can do to get this PR merged?

**Comment by peterkhayes** [comment]
Hi @jkirkwood - sorry for the delays. What has happened is that, when reviewing the PR, I looked at a lot of the old code, and realized how out of date it was. I've gotten most of the way through with a 1.0 release of this project, which:

* Converts the code to Typescript
* Uses async/await instead of callbacks, as well as other ES6 features
* Refactors the code to share logic between the different implementations
* Upgrades dependencies and tests with more recent Redis versions

My hope is that I'll be done by the end of this week, but should also probably just add your code in. The only thing I'd like to fix first is the Travis build.

**Comment by jkirkwood** [comment]
Thanks for the update @peterkhayes. Sounds like some great changes. I'd say if the update is only a week out, don't worry about merging my PR in. I'll be able to manage until then.

**Comment by peterkhayes** [comment]
Sorry for the delay. Life got in the way. The new version is released. You can check out the release notes [here](https://github.com/peterkhayes/rolling-rate-limiter#upgrading-from-01).

**Pull request closed without merging**
