### PR TITLE
Pull request storeblocked

### PR DESCRIPTION
**Pull request by pbwilmot**
I am looking for the ability to not store to the userSet if a given request is throttled.  This pull request adds a flag to options so that records are only stored to the userSet if they are blocked

### CODE REVIEW

**Comment by peterkhayes** [comment]
Hi pbwilmot - I'm not sure if your scheme is resistant to race conditions, since you make two non-independent requests to Redis in series. I'll consider adding this type of functionality, but it might require more warnings about what's happening.

**Comment by ORESoftware** [comment]
What type of race conditions are you trying to avoid exactly?

**Comment by peterkhayes** [comment]
See this blog post: https://engineering.classdojo.com/blog/2015/02/06/rolling-rate-limiter/

**Comment by jemhuntr** [comment]
Hi @peterkhayes. Is there a possibility to have this feature implemented somehow?

I'm using the module as a basic koa middleware and I'm a little frustrated that blocked actions count against the limits.

I'm not concerned with race conditions as I'm not sharing my limiters across servers. Although I believe it should still be possible to make this action atomic using transactions/watch on redis.

**Comment by peterkhayes** [comment]
@jemhuntr - I'm not really dedicating much time to this repo currently, except for any bug fixes that pop up.  If this is important to you, you should be able to fork the repo and merge this pull request in your fork.

**Comment by peterkhayes** [comment]
There is a new version of this library out. You can see the release notes [here](https://github.com/peterkhayes/rolling-rate-limiter#upgrading-from-01).

If this behavior is important to you, you can use `wouldLimit` to first check if an action would be blocked. If it would not be, then you can call `limit` and ignore the result.

**Pull request closed without merging**
