### PR TITLE
avoid unexpected rate limit on local out-of-sync timestamp

### PR DESCRIPTION
**Pull request by huayang-codaio**
with call to `wouldLimit`, the rate limiter would create a current timestamp with `microtime.now()` and use it with the timestamps fetched from Redis. 

This local `microtime.now()` however may be out of sync and be unexpected smaller than the latest timestamp on Redis. Even if it works right, another timestamp might be inserted into Redis between `getCurrentMicroseconds();` and `this.getTimestamps(id, false)`. 

This PR fixes the ordering of `getCurrentMicroseconds();` and `this.getTimestamps(id, false)`, and forces `minDifference` to only apply for positive values.

### CODE REVIEW

**Comment by peterkhayes** [comment]
I like this idea, but it looks like the tests are not passing on CI. Do they pass locally for you?

**Comment by huayang-codaio** [comment]
oh, sorry didn't notice that. let me take a look.

**Comment by peterkhayes** [comment]
Thanks for the fix! Published as [0.3.0](https://www.npmjs.com/package/rolling-rate-limiter) since it's technically a breaking change.

**Comment by huayang-codaio** [comment]
Appreciate @peterkhayes for the quick release!

**Pull request merged**
