### PR TITLE
fixes redis key TTL

### PR DESCRIPTION
**Pull request by stringang**
The value of the `interval` attribute of the `RateLimiter` class is in microseconds.

### CODE REVIEW

**Review by peterkhayes — APPROVED** [review]

**Comment by peterkhayes** [comment]
Thanks! Published as `0.2.9`

**Comment by Goues** [comment]
I'd like to ask about this. The readme says that this would be 60 seconds.

```
const limiter = new RedisRateLimiter({
	interval: 60000,
})
```

Do I need to change it to `60000000` when I update to 0.2.9?

**Comment by peterkhayes** [comment]
I don't think so, but this is a bit tricky to follow so I'll share my reasoning:

* I wanted to keep the `interval` configuration option as milliseconds, because this is the standard time value in the Javascript ecosystem (e.g. `setTimeout`).
* However, for accurate timing, this library uses microseconds under the hood.
* In the constructor for the base class `RateLimiter`, you can see that we call `millisecondsToMicroseconds` on the provided `interval` value. So the input value is in milliseconds, but the stored value is in microseconds.
* Then, in the constructor for the `RedisRateLimiter` class, we first call `super`, which sets `this.interval` (in microseconds). Then, we use `this.interval` to set the Redis TTL (in seconds). Therefore, the fix suggested by @stringang is correct.

**Comment by Goues** [comment]
Oh thank you!

After reading this I went to check the code again and I missed that there are two classes and one converts from milli to micro and then the other one from micro to seconds. 👍

**Pull request merged**
